### ISSUE TITLE
Doesn't create a dscl entry for a new user in Mojave

### ISSUE THREAD

**Issue by roadrunnersrg** [ninxsoft/MacUserGenerator#11] opened 2019-01-18 16:34 UTC
After testing here, another issue with this software is that (at least in Mojave 10.14.2) the app does not appear to be generating a "dscl" user, only a home folder.  The mac GUI does both when you create a new user in System Preferences-Users&Groups.

**Comment by ninxsoft** [comment] 2019-05-19 06:57
Support for Mojave is underway, will have some good news soon.

Duplicate of #7

**Closed as completed by ninxsoft** 2019-05-19 06:57 UTC
